version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    image: ddev-db:1.0
    restart: always
    secrets:
    - postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - back-tier
  api:
    image: ddev-api:1.0
    secrets:
    - source: postgres-password
      target: postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    networks:
    - back-tier
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
networks:
  back-tier: