version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    image: ${dockerID}/ddev_db
    build:
      context: database
    restart: always
    secrets:
    - postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: api
      dockerfile: Dockerfile-dev
    image: ${dockerID}/ddev_api
    ports:
      - "8080:8080"
      - "5005:5005"
    secrets:
    - source: postgres-password
      target: postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres

volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password






version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: ddev_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    build:
       context: api
    image: ddev_api
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier: